### PR TITLE
feat(dashboard) : back end call for appointment and patient, refresh list for same pages

### PR DESCRIPTION
**Pull request by SpiritGY**
# Description
- finished last sprint tasks, back end calls + refresh lists

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes
- Add back-end call for view, update and delete appointment
- Add back end call for view, update, create and delete patient
- Add refreshing list for patient page
- Add refreshing list for appointment page
- Adapt to the new back-end architecture
- adapt to new environment architecture

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Comment by Lucas-COX** [comment]
Task linked: [CU-86bx9vg3e Back-end rendez-vous](https://app.clickup.com/t/86bx9vg3e)

**Review by MarvinFlm — APPROVED** [review]
Good for me

**Review by lucas-louis — CHANGES_REQUESTED** [review]
For patients:
- The value of inputs need to start with an uppercase
- The height and the weight need to be multiply by 10
- In the medical info of a patient, the sex needs to be formated
For appointments:
- The info of the patient are not displayed
- When updating the appointment:
  - Bad size of illustration
  - For each days, the number of slots is not displayed
  - Why is there a colorred background
  - The update of slot is not working

**Review by lucas-louis — CHANGES_REQUESTED** [review]
For patients:
- The value of inputs need to start with an uppercase
- The height and the weight doesn't work when adding a new patient
- The value of the birthdate is wrong
- The chevron icon is too bold and maybe too big
- The name and firstname of the patient need to have the good fontWeight
- Too much padding on the right side of the patient card
- Missing border on patient card
- Weird white shadow in the modal of patient info

For appointments:
- Bad size of illustration when updating the appointment
- Missing available slots (slots of today??) when updating the appointment
- The number of slots need to be either plural or singular
- Weird arrow between the hours
- When displaying the appointments, there is a short laps time in order to get patient info so `null null` is displayed

**Review by lucas-louis — CHANGES_REQUESTED** [review]
No all inputs start with an uppercase even inputs that should not start with an uppercase such as email, password input...

For patients:
- The birthdate needs to be before the actual date

For appointments:
- "disponible" need to be either plural or singular based on the number of appointment available

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by MarvinFlm — APPROVED** [review]

**Pull request merged**
