### PR TITLE
Modify new conversation modal

### PR DESCRIPTION
**Pull request by MarvinFlm**
# Description

Modify modal for creation conversation patient to be the same of the figma 

### Click Up reference

[CU-86c0kfzwt](https://app.clickup.com/t/86c0kfzwt)

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Too much padding at the bottom of the modal
- The search is not fully working, sometimes the results are not showing (when opening/ closing the keyboard)
- Typo: "Ecriver" to "Ecrire"
- You can't send an empty message
- I can't create a new chat, the chat is not displayed

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- The search is not fully working, sometimes the results are not showing (when opening/ closing the keyboard)
- Typo: "Ecriver" to "Ecrire"
- The avatars are still squared

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Typo: "Ecriver" to "Ecrire" in create chat modal and in chat view

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Typo: "Ecriver" to "Ecrire" in chat view

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by SpiritGY — APPROVED** [review]

**Review by lucas-louis — APPROVED** [review]

**Review by SpiritGY — APPROVED** [review]

**Pull request merged**
