### PR TITLE
Cu 86bxcm996 fix te state of the app & navbar

### PR DESCRIPTION
**Pull request by MarvinFlm**
# Description

Fix the state on the app for reloading on add a new object in a list and modify the navbar to have more pages in the dashboard 
# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have added the needed labels
- [X] I have linked this PR to a clickup task
- [X] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Comment by Lucas-COX** [comment]
Task linked: [CU-86bxcm996 Fix te state of the app](https://app.clickup.com/t/86bxcm996)

**Review by SpiritGY — APPROVED** [review]
LGTM

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Update the description of the PR
I can't access to the app, I have a white screen

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Can't access to the dashboard??

When I try to connect I have a credential error and when I create an account I'm redirected to the landing page

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- The button to open the other tabs is not well clickable
- When there is no documents, an error is displayed on the document page

**Review by lucas-louis — APPROVED** [review]

**Pull request merged**
