### PR TITLE
Cu 86byva71f chat app doctor

### PR DESCRIPTION
**Pull request by SpiritGY**
# Description

adding chat pages

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Adding chatlist 

# Checklist

- [x] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Can't access to the chat ("Error loading patient name")

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Bad avatar
- The date is in English

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- No arrow on the back button
- The scroll is not efficient enough

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by MarvinFlm — APPROVED** [review]
LGTM

**Pull request merged**
