### PR TITLE
Cu 86byt079j UI navigation

### PR DESCRIPTION
**Pull request by MarvinFlm**
# Description

Remake the ui navigation with the go back on the previous page
# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- The icons are far too big
- Be careful, the main button on each page needs to be at the top now (like for the medical infos)
- Is it possible to avoid the sliding effect when changing of pages (the sliding effect is good but when you go from the first to the last page we see the other page and it doesn't look good)
- In the "more" menu:
  - The icon are too small
  - There is no name
  - The picture needs to use the boring-avatars picture
  - "Deconnexion" => "Déconnexion"
  - There is a white line at the top of the disconnect button
  - Not enough padding for the tab??
  - When the medical info is selected, the "more" button of the navbar is selected

Medical info:
- Too much padding between the label and the value
- "Anniversaire" => "Date de naissance"
- The primary doctor name is missing
- "Traitements" => "Antécédants médicaux et sujets de santé:"
- Too much border radius for the treatment cards?
- The size of the text is good?

Overall:
- There is now too much padding at the top of the screen

**Review by lucas-louis — CHANGES_REQUESTED** [review]
In the "more" menu:
- You need to provide a fix height when you load the info card of the patient to avoid having a moving card
- The name needs to be in uppercase
- The name is too big
- The return at the top need to have an arrow not a chevron
- The picture needs to use the same params as the one in the frontend
- "Deconnexion" => "Déconnexion"
- Too much x padding

Medical info:
- The primary doctor name needs to have "Dr. NAME Firstname"
Too much border radius for the treatment cards?

**Review by lucas-louis — CHANGES_REQUESTED** [review]
In the "more" menu:
- The picture needs to use the same params as the one in the frontend
- The icon are a bit too big

Medical info:
- You missed the space between "Dr." and the name of the patient

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Bad profile avatar, you invert the name and the firstname (same in the medical info)

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by SpiritGY — APPROVED** [review]

**Pull request merged**
