### PR TITLE
feat(patient): adding and modify medical folder

### PR DESCRIPTION
**Pull request by SpiritGY**
# Description
adding and update medical folder

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Updating UI for adding and update medical folder of the patient

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it.

### CODE REVIEW

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Did you change something on the input, because the inputs of the login page are not the same?
- You need to format the height and the weight
- The primary doctor is not displayed (even if there is one and it exists)
- The medical antecedents are not displayed

Updating:
- Typo "Sexe" => "Sex"
- The sex is not selected according to the actual medical info
- The weight and height needs to follow meters and kg
- If I empty a field, I can still go to the next step
- The background color of second step modal is not good (pink??)
- The medical antecedents are not displayed on the last step

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- The medical antecedents cards are not good

Updating:
- The background color of third step modal is not good (pink??)
- Border too big for the antecedents cards
- No padding for the button when adding a medical antecedent
- Grey shape under the medical antecedents
- Can't update the medical info (the validate button doesn't work) => the hitbox of the button is maybe bad
- The medical antecedents are duplicated when updating the medical info
- Once a medical antecedent added (and the medical info updated), we can't read the information of this medical antecedent in the medical info

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- When displaying the info a treatment, there is no space between the first label and the buttons

Updating:
- No scroll list on the last step
- Font weight not good

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by MarvinFlm — APPROVED** [review]
LGTM

**Pull request merged**
