### PR TITLE
feat(patient): page appointment

### PR DESCRIPTION
**Pull request by SpiritGY**
# Description

new appointment page

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

adding page appointment
can update and delete appoitment
can seee list of appointment with this patient

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Comment by Lucas-COX** [comment]
Task linked: [CU-86by15wp3 Page rendez-vous patient](https://app.clickup.com/t/86by15wp3)

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Delete appointment doesn't work

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- You need to provide a reason when cancelling an appointment

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by MarvinFlm — APPROVED** [review]
LGTM

**Pull request merged**
