### PR TITLE
Page de chat avec le medecin

### PR DESCRIPTION
**Pull request by MarvinFlm**
# Description

Create the websocket connexion

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by lucas-louis — DISMISSED** [review]

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- The navbar needs to have a top padding
- The date needs to be in the top of the card when there is no unread message

Chat:
- The divider needs to be thinner
- Go back arrow needs to be a bit bigger
- Too much spacing between the message
-

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- The date needs to be in french
- Bad name for the doctor (and so bad avatar)

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Bad name for the doctor (and so bad avatar)

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by SpiritGY — APPROVED** [review]

**Pull request merged**
