### PR TITLE
Cu 86bzn472v refont landing page and connexion page

### PR DESCRIPTION
**Pull request by MarvinFlm**
# Description

Refont Landing page and connexion page to fit of the new UI

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Landing page:
- The stroke needs to be a gradient not a plain white color

⚠️ Can't test the modals, the content doesn't load

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- The border needs to be only on the top of the card not on all the edge
- Still can't load the modals...

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Signup:
- Bad modal title
- The input needs to start by a lowercase

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by SpiritGY — APPROVED** [review]
Good

**Pull request merged**
