### PR TITLE
Cu 86c0ec5b9 nouvelle UI navbar patient

### PR DESCRIPTION
**Pull request by MarvinFlm**
# Description

Put the new UI on the nevbar to corrrespond of the  figma

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Missing x padding on the navbar

Santé:
- Too much padding at the top of the card
- Missing white background on the card
- Bad font weight and font size on the text

**Review by lucas-louis — CHANGES_REQUESTED** [review]
In the navbar:
- The text are a bit too small
- The icon are a bit too big

**Review by lucas-louis — CHANGES_REQUESTED** [review]
In the navbar:
- The text doesn't have the good weight
- The icon are still a bit too big

> Check the navbar of the doctor app

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by SpiritGY — APPROVED** [review]

**Pull request merged**
