### PR TITLE
Cu 86bzewfu9 page 2 fa medecin

### PR DESCRIPTION
**Pull request by SpiritGY**
# Description

adding account page

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

new Account page and navigation to it 

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Is it possible to add a blue border around the profile picture?
- The blue card needs to has all the corner rounded
- Good font weight for the title of section?
- Missing divider between the tabs
- Missing birth date inside the blue profile card
- Missing vertical padding on section
- Too much padding on the right of the arrow?
- Is the text of the page centered?

Account:
- Missing divider between tabs
- Bad color for email placeholder

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Profile page:
- The divider between the tabs is too thick

Account:
- The back arrow doesn't work

**Review by lucas-louis — CHANGES_REQUESTED** [review]
The divider between the tabs is too thick on all the pages
image

**Review by lucas-louis — DISMISSED** [review]
LGTM

**Review by MarvinFlm — DISMISSED** [review]
Good

**Review by MarvinFlm — APPROVED** [review]
good

**Review by lucas-louis — APPROVED** [review]

**Pull request merged**
