### PR TITLE
Cu 86by8p471 page traitement

### PR DESCRIPTION
**Pull request by MarvinFlm**
# Description

This is the page of traitement with the add , modification , delete.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Too much padding x on the card of the medicine of a treatment
- Decrease the padding x on the treatment card

Add a treatment:
- Bad modal when adding a treatment

Update a treatment:
- Can access to the view => grey square

Delete the treatments:
- Typo on "Supprimer le traitement" => "Supprimer les traitements"

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Too much padding x on the card of the medicine of a treatment
- Decrease the padding x on the treatment card
- Problem when the treatments are too large

Update a treatment:
- Can access to the view => grey square

Delete a treatment
- Can't delete a treatment

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Update a treatment:
- Can't access to the view => grey square

Add a treatment:
- When selecting "Yes" for the medical antecedent and then selecting "No" the select input is still displayed

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Add a treatment:
- Can't access to the view => grey square

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- No automatic reload when adding a treatment

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- "Mes traitement" => "Mes traitements"
- Bad date sent to the backend when checking a treatment

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by SpiritGY — APPROVED** [review]

**Pull request merged**
