### PR TITLE
fix: problem modal and other

### PR DESCRIPTION
**Pull request by MarvinFlm**
# Description

Resolve problem of the modal with the new version of the flutter

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Can't remove a document from the favorite
 - Input too thin
 - Filter => "Ordonnance": bad color
 - Not enough spacing on the sort option
 - "Ajouter des filtres" not enough spacing with the plus icon and bad weight
 - Add a document button too small
 - No auto reload when updating the document
 - Can't download the file
 - "Mes Documents" => "Mes documents"

Add document modal:
- Too big button
- Can't add a document

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Can't remove a document from the favorite
- Filter => "Ordonnance": bad color
- No delete document?
- No auto reload when updating the document
- Can't download the file (sometime)

Add document modal:
- Too big button
- Can't add a document (the modal closes but no document are added)

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Can't remove a document from the favorite
- The search bar doesn't work

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by SpiritGY — APPROVED** [review]

**Pull request merged**
