### PR TITLE
Cu 86bxxwf08 page de confirmation

### PR DESCRIPTION
**Pull request by MarvinFlm**
# Description

Page confirmation rendez vous
# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Comment by Lucas-COX** [comment]
Task linked: [CU-86bxxwf08 Page de confirmation](https://app.clickup.com/t/86bxxwf08)

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Can't test, the app doesn't build

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Can't test => white screen after login

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by SpiritGY — APPROVED** [review]

**Pull request merged**
