### PR TITLE
Cu 86by953fd page pr diagnostic

### PR DESCRIPTION
**Pull request by SpiritGY**
# Description

Diagnostic section on dashboard

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

adding diagnostic pages + features, and adding diagnostic view on appointment

# Checklist

- [x] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it.

### CODE REVIEW

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- "Mes Diagnostics" -> "Mes diagnostics"
- Too much spacing between the banner and the buttons
- Bad font size for the text of the buttons (the one under the banner)
- No auto reload when the diagnostic is accepted
- The diagnostic needs to be sorted by date
- You can't refused a diagnostic without filling the input
- The loading circle are weird when there is more than one element
- 

Diagnostic card:
- Too much spacing between the name of the patient and the date
- Bad font for the text
- The font size of the date is good?
- Missing right chevron

Modal:
- "Dossier Médical" -> "Dossier médical"
- The buttons to validate/ refuse the diagnostic need to be displayed only when the diagnostic is not reviewed

Diagnostic Modal:
- Bad font weight for the title + "Back" button
- Is it possible to round the linear progress bar?

Cancel Modal:
- Missing "." at the end of the modal description
- The input have not the good height
- The placeholder is too big
- The label of the inputs need to be aligned on the left

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- Bad font size for the text of the buttons (the one under the banner)

Diagnostic card:
- Too much spacing between the name of the patient and the date
- Bad font for the text
- The font size of the date is good?

Modal:
- Can't close the modal by clicking outside of it

Diagnostic Modal:
- Bad font weight for the title + "Back" button

**Review by lucas-louis — CHANGES_REQUESTED** [review]
⚠️ Bad input height on login

Diagnostic card:
Bad font size for the name of the patient?

Medical info modal:
- All the text is bolded

Can't access to the chat

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- No primary doctor displayed
- Card: Firstname NAME
- Modal banner card label font weight too bold

**Review by MarvinFlm — APPROVED** [review]
LGTM

**Pull request merged**
