### PR TITLE
feat(patient): patient navigation

### PR DESCRIPTION
**Pull request by SpiritGY**
# Description

setting up patient navigation

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

adding navigation
setting temporary pages for exemple

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Comment by Lucas-COX** [comment]
Task linked: [CU-86bxmtg2d Initialisation page intermediaire patient](https://app.clickup.com/t/86bxmtg2d)

**Review by MarvinFlm — DISMISSED** [review]

**Review by lucas-louis — CHANGES_REQUESTED** [review]
Modal:
- The name is a bit too bolded? (maybe)
- Too much padding on the right of each element (right to the arrow)
- The arrow is not enough bold
- Could you check if the colors are good (background)?
- When deleting a patient, the cancel button is not working

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by lucas-louis — CHANGES_REQUESTED** [review]
- There is no patients displayed in the page => maybe because the backend has updated the return value of the route

**Review by lucas-louis — DISMISSED** [review]
⚠️ When the medical info is selected for a patient, the disconnection tab is selected in the navbar

+ when a patient is removed, the list is not automatic updated

**Review by lucas-louis — APPROVED** [review]
LGTM

**Review by MarvinFlm — APPROVED** [review]

**Pull request merged**
